version: '3'

services:

  db:
    container_name: db_1
    image: mysql:8.0.12
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=spark
    - MYSQL_USER=spark
    - MYSQL_PASSWORD=spark
    volumes:
    - "mysql:/var/lib/mysql"
    ports:
    - "3306:3306"

    networks:
    - spark-network



  spark:
    container_name: spark_1
    depends_on:
    - db
    build: .
    ports:
    - "3000:3000"
    - "8888:8888"
    - "8889:8889"
    - "4040:4040"

    environment:
    - ALLOW_POPULATE_DB=yes
    - SPARK_DB_CLIENT=mysql
    - SPARK_DB_HOSTNAME=db
    - SPARK_DB_DBNAME=spark
    - SPARK_DB_USER=spark
    - SPARK_DB_PASSWORD=spark
    - SPARK_DB_DEBUG=false
    - SPARK_SERVER_PORT=3000
    - SPARK_SERVER_HOSTNAME=localhost
    - SPARK_SERVER_PROTOCOL=http
    - SPARK_SERVER_URL=http://localhost:3000
    - SPARK_MAILSERVER_ENABLE=false
    - SPARK_RECAPTCHA_IGNORE=true
    - GRANT_SUDO=yes 
 
    volumes:
    - ./work:/home/jovyan/work
    - ./data:/home/jovyan/data


    networks:
    - spark-network


networks:
  spark-network:
    driver: bridge



volumes:
  mysql:

